base: [services] Fix weird launcher3 crash
Fixes:
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
Caused by: android.os.RemoteException: Remote stack trace:
at com.android.server.wm.Task.lambda$applyAnimationUnchecked$13(Task.java:3355)

Change-Id: I580ecac54de4bad9a3af4e68e73477a0b3bdc2d5
Signed-off-by: Pranav Vashi <neobuddy89@gmail.com>
Signed-off-by: Aston-Martinn <advaithbhat9@gmail.com>